hellomake: hellomake.c hellofunc.c
	gcc -o hellomake hellomake.c hellofunc.c -I/Users/sagarsingh/Documents/isocpp/Makefile/2/
	# -I represent path where include file is present #include <hellomake.h> TODO: see here ange brackets and no " "
